# Generated by Django 3.1.6 on 2024-07-31 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=1000, unique=True)),
                ('details', django_summernote.fields.SummernoteTextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(blank=True, max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('website_link', models.TextField(blank=True)),
                ('details', django_summernote.fields.SummernoteTextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreConstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy', models.CharField(max_length=500)),
                ('no_of_units', models.CharField(max_length=500)),
                ('project_name', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=1000, unique=True)),
                ('price_starting_from', models.FloatField(default=0)),
                ('price_to', models.FloatField(default=0)),
                ('project_type', models.CharField(choices=[('Condo', 'Condo'), ('Townhome', 'Townhome'), ('Semi-Detached', 'Semi-Detached'), ('Detached', 'Detached'), ('NaN', 'NaN')], default='NaN', max_length=500)),
                ('description', django_summernote.fields.SummernoteTextField(blank=True)),
                ('project_address', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Selling', 'Selling'), ('Archived', 'Archived'), ('Planning Phase', 'Planning Phase'), ('Sold out', 'Sold out')], default='Upcoming', max_length=500)),
                ('co_op_available', models.BooleanField(default=False)),
                ('date_of_upload', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preconstruction.city')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preconstruction.developer')),
            ],
            options={
                'ordering': ['-last_updated', django.db.models.expressions.Case(django.db.models.expressions.When(status='Selling', then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(status='Upcoming', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(status='Sold out', then=django.db.models.expressions.Value(3)), default=django.db.models.expressions.Value(4), output_field=models.IntegerField())],
            },
        ),
        migrations.CreateModel(
            name='PreConstructionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('preconstruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='preconstruction.preconstruction')),
            ],
        ),
        migrations.CreateModel(
            name='PreConstructionFloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorplan', models.FileField(upload_to='')),
                ('preconstruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorplan', to='preconstruction.preconstruction')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=1000)),
                ('slug', models.CharField(blank=True, max_length=1000)),
                ('news_thumbnail', models.FileField(blank=True, upload_to='')),
                ('news_description', django_summernote.fields.SummernoteTextField(blank=True)),
                ('date_of_upload', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('news_link', models.CharField(default='#', max_length=2000)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preconstruction.city')),
            ],
        ),
    ]
